# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ba7712d0734f445c2459a607fbe7fe726817986ed42ab94896011cdb0a22187c36c15b391d0393c887fd6a7295f685414d92ac51fbfa4b97b60831654421973

test:
  secret_key_base: 8252c7837ae900ac2c5cbe0b10e56eacaf20138fe27772786a941e0f42dd444951e3ac3847e4ff364ec92748ce4761563a708324ce2be0f727bf3d8b4c0abfe3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
